<?php
/**
 * This file is generated by bin/translate.js
 * Do not edit this file manually.
 */

return array(
	'Select a category from'                        => __( 'Select a category from', 'amve_lang' ),
	'or a keyword (if it is available)'             => __( 'or a keyword (if it is available)', 'amve_lang' ),
	'Select a WordPress category'                   => __( 'Select a WordPress category', 'amve_lang' ),
	'AND'                                           => __( 'AND', 'amve_lang' ),
	'Check at least 1 video'                        => __( 'Check at least 1 video', 'amve_lang' ),
	'to enable this button'                         => __( 'to enable this button', 'amve_lang' ),
	'Import'                                        => __( 'Import', 'amve_lang' ),
	'videos and save this search as a Feed. All your Feeds are displayed at the bottom of this page.' => __( 'videos and save this search as a Feed. All your Feeds are displayed at the bottom of this page.', 'amve_lang' ),
	'An error occurred while trying to retrieve generated content' => __( 'An error occurred while trying to retrieve generated content', 'amve_lang' ),
	'Sorry, our AI server is currently overloaded.' => __( 'Sorry, our AI server is currently overloaded.', 'amve_lang' ),
	'Please try again in a few seconds.'            => __( 'Please try again in a few seconds.', 'amve_lang' ),
	'No WPS-Credit have been used.'                 => __( 'No WPS-Credit have been used.', 'amve_lang' ),
	'We apologize for the inconvenience.'           => __( 'We apologize for the inconvenience.', 'amve_lang' ),
	'An error occurred while trying to retrieve generated content.' => __( 'An error occurred while trying to retrieve generated content.', 'amve_lang' ),
	'Saving Options'                                => __( 'Saving Options', 'amve_lang' ),
	'Save Options'                                  => __( 'Save Options', 'amve_lang' ),
	'Delete this feed'                              => __( 'Delete this feed', 'amve_lang' ),
	'From the category or tag'                      => __( 'From the category or tag', 'amve_lang' ),
	'to the WordPress category'                     => __( 'to the WordPress category', 'amve_lang' ),
	'Category removed'                              => __( 'Category removed', 'amve_lang' ),
	'Videos imported:'                              => __( 'Videos imported:', 'amve_lang' ),
	'Last update:'                                  => __( 'Last update:', 'amve_lang' ),
	'Last page visited:'                            => __( 'Last page visited:', 'amve_lang' ),
	'Change videos status when importing'           => __( 'Change videos status when importing', 'amve_lang' ),
	'Import the videos as Published'                => __( 'Import the videos as Published', 'amve_lang' ),
	'Import the videos as Draft'                    => __( 'Import the videos as Draft', 'amve_lang' ),
	'Enable or disable auto-import'                 => __( 'Enable or disable auto-import', 'amve_lang' ),
	'Enable auto import'                            => __( 'Enable auto import', 'amve_lang' ),
	'Disable auto import'                           => __( 'Disable auto import', 'amve_lang' ),
	'Enable or disable outgoing links'              => __( 'Enable or disable outgoing links', 'amve_lang' ),
	'Enable outgoing links'                         => __( 'Enable outgoing links', 'amve_lang' ),
	'Disable outgoing links'                        => __( 'Disable outgoing links', 'amve_lang' ),
	'Search new videos'                             => __( 'Search new videos', 'amve_lang' ),
);
